name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check documentation links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --exclude-mail docs
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest black isort pre-commit
      - name: Install Playwright browsers
        run: python -m playwright install chromium
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci --no-progress
      - name: Import smoke test
        run: python tools/import_sanity_check.py
      - name: Run tests
        run: DISABLE_PDF_RENDER=true pytest -q
